In [1]:
"""
backpropagationのデモ
"""


class AddLayer:
    def forward(self, x, y):
        z = x+y
        return z
    def backward(self):
        # dz/dx, dz/dy
        return 1., 1.
    
class MulLayer:
    def forward(self, x, y):
        self.x = x
        self.y = y
        z = x*y
        return z
    def backward(self):
        # dz/dx, dz/dy
        return self.y, self.x
    
class MulTwoLayer:
    def forward(self, x):
        self.x = x
        z = 2.*x
        return z
    def backward(self):
        # dz/dx
        return 2.

a = 3.
b = 1.
c = -2.

add = AddLayer()
mul_two = MulTwoLayer()
mul = MulLayer()

d = mul_two.forward(b)
e = add.forward(a, d)
L = mul.forward(c, e)

dLdc, dLde = mul.backward()
deda, dedd = add.backward()
dLda = dLde*deda
dLdd = dLde*dedd
dddb = mul_two.backward()
dLdb = dLdd*dddb

print(dLda)
print(dLdb)
print(dLdc)

-2.0
-4.0
5.0


In [2]:
import torch


a = torch.tensor([3.], requires_grad=True)
b = torch.tensor([1.], requires_grad=True)
c = torch.tensor([-2.], requires_grad=True)
d = 2.*b
e = a+d
L = c*e

L.backward()

print(a.grad)
print(b.grad)
print(c.grad)

tensor([-2.])
tensor([-4.])
tensor([5.])
