In [34]:
"""
pytorchのautogradで勾配を計算する
"""

import torch


a = torch.tensor([3.], requires_grad=True)
b = torch.tensor([1.], requires_grad=True)
c = torch.tensor([-2.], requires_grad=True)
d = 2.*b
e = a+d
L = c*e

L.backward()

print(a.grad)
print(b.grad)
print(c.grad)

tensor([-2.])
tensor([-4.])
tensor([5.])
